package com.gobenefit.db;

public interface DBConstant {

	String SERVICE_TABLE = "PT_SERVICE";

	String APARTMENT_TABLE = "APARTMENT";

	String TOWER_TABLE = "TOWER";

	String CLUB_TABLE = "CLUB";

	String LOOKUP_CODE_TABLE = "LOOKUP_CODE";

	String ADDRESS_TABLE = "ADDRESS";

	String USER_ROLE_TABLE = "USER_ROLE";

	String USER_TABLE = "USER";

	String SERVICE_REQUEST_TABLE = "SERVICE_REQUEST";

	String EVENT_BOOKING_TABLE = "EVENT_BOOKING";

	String SERVICE_REQUEST_COMMENTS_TABLE = "SERVICE_REQUEST_COMMENTS";

	String FLAT_TABLE = "FLAT";

	String FLAT_USER_RELATIONSHIP = "FLAT_USER_RELATIONSHIP";

	String USER_ACTIVATION_TABLE = "USER_ACTIVATION";

	String APARTMENT_FACILITY_TABLE = "APARTMENT_FACILITY";

	String APARTMENT_FACILITY_RELATIONSHIP_TABLE = "APARTMENT_FACILITY_RELATIONSHIP";
}
