USE GOBENEFITS;

-- Setting up the data for Country
DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='COUNTRY' AND CODE!='-1';
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('INDIA', 'India', 'India', 'COUNTRY', null, 1);


-- Setting up the data for States
DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='STATE' AND CODE!='-1';
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('UTTARPRADESH', 'Uttar Pradesh', 'Uttar Pradesh', 'STATE', 'INDIA', 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('HARYANA', 'Haryana', 'Haryana', 'STATE', 'INDIA', 1);


-- Setting up the data for Cities
DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='CITY' AND CODE!='-1';
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('NOIDA', 'Noida', 'Noida', 'CITY', 'UTTARPRADESH', 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('GHAZIABAD', 'Ghaziabad', 'Ghaziabad', 'CITY', 'UTTARPRADESH', 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('GURGAON', 'Gurgaon', 'Gurgaon', 'CITY', 'HARYANA', 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('FARIDABAD','Faridabad','Faridabad', 'CITY', 'HARYANA',1);

-- Setting up the user status
DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='USER_STATUS' AND CODE!='-1';
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('ACTIVE', 'Active', 'Active', 'USER_STATUS', null, 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('PENDING_RWA', 'Pending from RWA Activation', 'Pending from RWA Activation', 'USER_STATUS', null, 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('DEACTIVE','De-active','De-active', 'USER_STATUS', null,1);

-- Setting up the user type
DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='USER_GENDER' AND CODE!='-1';
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('MALE', 'Male', 'Male', 'USER_GENDER', null, 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('FEMALE','Female','Female', 'USER_GENDER', null,1);


-- Setting up the service request status
DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='SERVICE_REQUEST_STATUS' AND CODE!='-1';
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('OPEN', 'Open', 'Once user will create the service, Open status would be assigned to that request.', 'SERVICE_REQUEST_STATUS', null, 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('PENDING', 'Pending', 'After the assignment of service provider, status would be changed to pending.', 'SERVICE_REQUEST_STATUS', null, 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('IN_PROGRESS', 'In Progress', 'When service provider will start working, it should be in In Progress status.', 'SERVICE_REQUEST_STATUS', null, 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('CLOSED','Closed','Succesfully completed the service request.', 'SERVICE_REQUEST_STATUS', null,1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('REOPENED','Re-opened','If the user is not satisfied with resolution then request can be reopened and status would be Re-opened.', 'SERVICE_REQUEST_STATUS', null,1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('CANNOT_FIX','Cannot Fix','If the service request cannot be fixed due to some issue this then the status should be Cannot Fix.', 'SERVICE_REQUEST_STATUS', null,1);

-- Setting up the apartment status
 DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='APARTMENT_STATUS' AND CODE!='-1';
 INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('ACTIVED', 'Actived', 'Actived', 'APARTMENT_STATUS', null, 1);
 INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('DEACTIVED','Deactived','Deactived', 'APARTMENT_STATUS', null,1);

 -- Setting up the apartment status
 DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='APARTMENT_FACILITY' AND CODE!='-1';
 INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('BASIC_AMINITIES', 'Basic Aminities', 'Basic Aminities', 'APARTMENT_FACILITY', null, 1);
 INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('ADVANCE_AMINITIES','Advance Aminities','Advance Aminities', 'APARTMENT_FACILITY', null,1);
 -- Setting up the Booking status
DELETE FROM LOOKUP_CODE WHERE GROUP_CODE='BOOKING_STATUS' AND CODE !='-1';
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('NEW', 'New', 'New', 'BOOKING_STATUS', null, 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('REJECTED', 'Rejected', 'Rejected', 'BOOKING_STATUS', null, 1);
INSERT INTO LOOKUP_CODE(CODE, VALUE, DESCRIPTION, GROUP_CODE, PARENT_CODE, IS_ACTIVE) VALUES ('APPROVED', 'Approved', 'Approved', 'BOOKING_STATUS', null, 1);
 
 -- Settinn up the facilities
 DELETE FROM APARTMENT_FACILITY WHERE CODE!='-1';
 INSERT INTO APARTMENT_FACILITY(NAME, CODE, DESCRIPTION) VALUES ('Club', 'CL', null);
 INSERT INTO APARTMENT_FACILITY(NAME, CODE, DESCRIPTION) VALUES ('Tower', 'TO', null);
 INSERT INTO APARTMENT_FACILITY(NAME, CODE, DESCRIPTION) VALUES ('Shopping Complex', 'SC', null);
 INSERT INTO APARTMENT_FACILITY(NAME, CODE, DESCRIPTION) VALUES ('Canteen', 'CA', null);
 INSERT INTO APARTMENT_FACILITY(NAME, CODE, DESCRIPTION) VALUES ('Parking', 'PR', null);
 INSERT INTO APARTMENT_FACILITY(NAME, CODE, DESCRIPTION) VALUES ('Lift', 'LF', null);
 
 
-- Setting up the user roles
 DELETE FROM USER_ROLE WHERE ROLE !='-1' ;
 INSERT INTO USER_ROLE (ROLE, NAME, DESCRIPTION, IS_ACTIVE) VALUES ('APP_ADMIN', 'Application Admin', 'This role will be assign to the user, who will manage the application.', 1);
 INSERT INTO USER_ROLE (ROLE, NAME, DESCRIPTION, IS_ACTIVE) VALUES ('RWA_ADMIN', 'RWA Admin', 'Role for RWA admin, who manage the society.', 1);
 INSERT INTO USER_ROLE (ROLE, NAME, DESCRIPTION, IS_ACTIVE) VALUES ('SERVICE_PROVIDER', 'Technician', 'This role will be assign to the users who will be providing the services for user requests.', 1);
 INSERT INTO USER_ROLE (ROLE, NAME, DESCRIPTION, IS_ACTIVE) VALUES ('OWNER', 'House Owner', 'This role will be assign to the user, who will own the house.', 1);
 INSERT INTO USER_ROLE (ROLE, NAME, DESCRIPTION, IS_ACTIVE) VALUES ('TENANT', 'Tenan', 'This role will be assign to the user, who will be living in society as tenant.', 1);
 

 --Setup the default entities
 DELETE FROM FLAT WHERE APARTMENT_ID=-1;
 DELETE FROM APARTMENT WHERE ID=-1;

 INSERT INTO APARTMENT VALUES (-1,NOW(), NOW(), 0, 'Default Apartment', null);
 INSERT INTO FLAT VALUES (-1,NOW(), NOW(), 0, 0, null, -1, NULL);
 
