ALTER TABLE `gobenefits`.`user` CHANGE COLUMN `NAME` `FIRST_NAME` VARCHAR(32) NOT NULL  , ADD COLUMN `LAST_NAME` VARCHAR(28) NULL  AFTER `STATUS` ;
UPDATE flat_user_relationship SET STATUS='ACTIVE' WHERE ID != -1;
UPDATE user SET STATUS='ACTIVE' WHERE ID != -1;
ALTER TABLE `gobenefits`.`lookup_code` CHANGE COLUMN `ID` `ID` BIGINT(20) NOT NULL AUTO_INCREMENT  ;
